/**
 * Artboxes ui-agent config — generated by examples/generate-config-prompt.md
 *
 * Copy to ui-visual-agent repo root:
 *   cp examples/artboxes-config.ts ui-agent.config.ts
 * Then update the import path:
 *   "../src/runner/types.js"  →  "./src/runner/types.js"
 *
 * Required env vars (add to GitHub Actions secrets/variables):
 *   WEB_URL        — e.g. https://artboxes.io           (web app)
 *   ARTIST_URL     — e.g. https://artist.artboxes.io    (artist portal)
 *   PRELAUNCH_URL  — e.g. https://pre.artboxes.io       (pre-launch site)
 *
 * Locally: add to .env (falls back to localhost defaults if unset)
 *
 * ── False-positive skip registry ──────────────────────────────────────────
 * #8   empty section visible in viewport (below-fold or auth-wall content)
 * #9   text clipped at container/viewport edge
 * #10  text "overflows" — background content visible behind an open modal, clipped at viewport edge
 * #11  text truncated with ellipsis
 * #16  low-contrast text — Artboxes brand uses intentionally muted tones
 * #20  broken or missing image (CDN not yet loaded at screenshot time)
 * #22  image clipped by container edge (visible in background behind modal)
 * #23  placeholder/skeleton element visible during loading
 * #36  active nav item has no visual differentiation — intentional nav design
 * #38  skeleton card with no content (loading state)
 * #39  icon+text "slightly" misaligned — sub-pixel rendering difference, not a real layout bug
 * #43  modal overlay appears transparent — Privy auth modal and brand scrim style
 * #46  mixed icon fill/outline styles — Home icon is intentionally filled (active)
 * #48  skeleton placeholder grid
 * #49  empty space / missing empty-state (loading or auth-wall)
 * #50  skeleton loading indicator
 */
/**
 * Artboxes ui-agent config
 *
 * Required env vars (add to GitHub Actions secrets/variables):
 *   WEB_URL     — e.g. https://artboxes.io           (web app)
 *   ARTIST_URL  — e.g. https://artist.artboxes.io    (artist portal)
 *
 * Locally: add to .env (falls back to localhost defaults if unset)
 */
import type { AgentConfig } from "./src/runner/types.js";

const WEB_URL = process.env.WEB_URL ?? "http://localhost:3000";
const ARTIST_URL = process.env.ARTIST_URL ?? "http://localhost:3001";

const config: AgentConfig = {
  // ── Global false positives ───────────────────────────────────────────────
  // See registry above for explanations.
  globalSkipIssueIds: [3, 7, 9, 10, 11, 12, 15, 22, 27, 32, 34, 36, 39, 43],

  scenarios: [
    // ── WEB APP ──────────────────────────────────────────────────────────────

    {
      label: "Web / Home — mobile",
      url: `${WEB_URL}/`,
      filePath: "apps/web/app/page.tsx",
      viewport: { width: 375, height: 812 },
    },
    {
      label: "Web / Home — desktop",
      url: `${WEB_URL}/`,
      filePath: "apps/web/app/page.tsx",
      viewport: { width: 1280, height: 800 },
    },
    {
      label: "Web / Home — tablet",
      url: `${WEB_URL}/`,
      filePath: "apps/web/app/page.tsx",
      viewport: { width: 768, height: 1024 },
    },

    {
      label: "Web / Collections — mobile",
      url: `${WEB_URL}/collections`,
      filePath: "apps/web/app/collections/page.tsx",
      viewport: { width: 375, height: 812 },
      // CDN images and skeleton cards are not loaded at screenshot time
      skipIssueIds: [8, 20, 23, 38, 49, 50],
    },
    {
      label: "Web / Collections — desktop",
      url: `${WEB_URL}/collections`,
      filePath: "apps/web/app/collections/page.tsx",
      viewport: { width: 1280, height: 800 },
      skipIssueIds: [8, 20, 23, 38, 48, 49, 50],
    },

    {
      label: "Web / Upcoming — mobile",
      url: `${WEB_URL}/upcoming`,
      filePath: "apps/web/app/upcoming/page.tsx",
      viewport: { width: 375, height: 812 },
    },
    {
      label: "Web / Upcoming — desktop",
      url: `${WEB_URL}/upcoming`,
      filePath: "apps/web/app/upcoming/page.tsx",
      viewport: { width: 1280, height: 800 },
      // gradient/blank placeholder cards while CDN images load
      skipIssueIds: [8, 20, 23, 38],
    },

    // Marketplace — unauthenticated shows a sign-in wall
    {
      label: "Web / Marketplace — mobile (unauthed)",
      url: `${WEB_URL}/marketplace`,
      filePath: "apps/web/app/marketplace/page.tsx",
      viewport: { width: 375, height: 812 },
      // #16: brand subtitle text uses intentionally muted color on beige background
      skipIssueIds: [8, 16, 49],
    },
    {
      label: "Web / Marketplace — desktop (unauthed)",
      url: `${WEB_URL}/marketplace`,
      filePath: "apps/web/app/marketplace/page.tsx",
      viewport: { width: 1280, height: 800 },
      // #23: CDN images still loading in marketplace grid at screenshot time
      skipIssueIds: [8, 23, 49],
    },
    {
      label: "Web / Marketplace — wide desktop",
      url: `${WEB_URL}/marketplace`,
      filePath: "apps/web/app/marketplace/page.tsx",
      viewport: { width: 1440, height: 900 },
      skipIssueIds: [8, 23, 49],
    },

    // Auth-required pages — render a Privy sign-in wall when unauthenticated
    {
      label: "Web / Dashboard — mobile (unauthed)",
      url: `${WEB_URL}/dashboard`,
      filePath: "apps/web/app/dashboard/page.tsx",
      viewport: { width: 375, height: 812 },
      skipIssueIds: [8, 49],
    },
    {
      label: "Web / Dashboard — desktop (unauthed)",
      url: `${WEB_URL}/dashboard`,
      filePath: "apps/web/app/dashboard/page.tsx",
      viewport: { width: 1280, height: 800 },
      skipIssueIds: [8, 49],
    },
    {
      label: "Web / Profile — mobile (unauthed)",
      url: `${WEB_URL}/profile`,
      filePath: "apps/web/app/profile/page.tsx",
      viewport: { width: 375, height: 812 },
      // #16: "Sign in to view your…" uses intentionally muted brand color on beige
      skipIssueIds: [8, 16, 49],
    },
    {
      label: "Web / Wallet — mobile (unauthed)",
      url: `${WEB_URL}/wallet`,
      filePath: "apps/web/app/wallet/page.tsx",
      viewport: { width: 375, height: 812 },
      skipIssueIds: [8, 16, 49],
    },
    {
      label: "Web / History — mobile (unauthed)",
      url: `${WEB_URL}/history`,
      filePath: "apps/web/app/history/page.tsx",
      viewport: { width: 375, height: 812 },
      skipIssueIds: [8, 16, 49],
    },
    {
      label: "Web / Shipping — mobile (unauthed)",
      url: `${WEB_URL}/shipping`,
      filePath: "apps/web/app/shipping/page.tsx",
      viewport: { width: 375, height: 812 },
      skipIssueIds: [8, 16, 49],
    },

    // FAQ — accordion toggles are icon-only by design (#46)
    {
      label: "Web / FAQ — mobile",
      url: `${WEB_URL}/faq`,
      filePath: "apps/web/app/faq/page.tsx",
      viewport: { width: 375, height: 812 },
      skipIssueIds: [46],
    },
    {
      label: "Web / FAQ — desktop",
      url: `${WEB_URL}/faq`,
      filePath: "apps/web/app/faq/page.tsx",
      viewport: { width: 1280, height: 800 },
      skipIssueIds: [46],
    },

    {
      label: "Web / Blog — mobile",
      url: `${WEB_URL}/blog`,
      filePath: "apps/web/app/blog/page.tsx",
      viewport: { width: 375, height: 812 },
    },
    {
      label: "Web / Blog — desktop",
      url: `${WEB_URL}/blog`,
      filePath: "apps/web/app/blog/page.tsx",
      viewport: { width: 1280, height: 800 },
      // sparse grid with few articles is expected content, not a layout bug
      skipIssueIds: [8],
    },

    // Simple / text-only pages — mobile only
    {
      label: "Web / About — mobile",
      url: `${WEB_URL}/about`,
      filePath: "apps/web/app/about/page.tsx",
      viewport: { width: 375, height: 812 },
    },
    {
      label: "Web / Careers — mobile",
      url: `${WEB_URL}/careers`,
      filePath: "apps/web/app/careers/page.tsx",
      viewport: { width: 375, height: 812 },
    },
    {
      label: "Web / Contact — mobile",
      url: `${WEB_URL}/contact`,
      filePath: "apps/web/app/contact/page.tsx",
      viewport: { width: 375, height: 812 },
      skipIssueIds: [8],
    },
    {
      label: "Web / Learn — mobile",
      url: `${WEB_URL}/learn`,
      filePath: "apps/web/app/learn/page.tsx",
      viewport: { width: 375, height: 812 },
    },
    {
      label: "Web / Help — mobile",
      url: `${WEB_URL}/help`,
      filePath: "apps/web/app/help/page.tsx",
      viewport: { width: 375, height: 812 },
    },
    // Still under active development — medium threshold to reduce noise
    {
      label: "Web / Developers — mobile",
      url: `${WEB_URL}/developers`,
      filePath: "apps/web/app/developers/page.tsx",
      viewport: { width: 375, height: 812 },
      severityThreshold: "medium",
    },
    {
      label: "Web / Docs — mobile",
      url: `${WEB_URL}/docs`,
      filePath: "apps/web/app/docs/page.tsx",
      viewport: { width: 375, height: 812 },
      severityThreshold: "medium",
    },
    {
      label: "Web / Privacy — mobile",
      url: `${WEB_URL}/privacy`,
      filePath: "apps/web/app/privacy/page.tsx",
      viewport: { width: 375, height: 812 },
    },
    {
      label: "Web / Terms — mobile",
      url: `${WEB_URL}/terms`,
      filePath: "apps/web/app/terms/page.tsx",
      viewport: { width: 375, height: 812 },
    },

    // 404 page — sparse by design, large gap above error message is intentional
    {
      label: "Web / 404 page — mobile",
      url: `${WEB_URL}/this-page-does-not-exist`,
      filePath: "apps/web/app/not-found.tsx",
      viewport: { width: 375, height: 812 },
      skipIssueIds: [8, 49],
    },

    // ── WEB APP — MODALS ─────────────────────────────────────────────────────

    // Sign-in modal (Privy) — overlay and background artefacts covered globally
    {
      label: "Web / Sign in modal — mobile",
      url: `${WEB_URL}/`,
      filePath: "apps/web/components/auth/SignInModal.tsx",
      viewport: { width: 375, height: 812 },
      steps: [
        { action: "click", selector: "button:has-text('Sign in')" },
        { action: "wait", ms: 600 },
      ],
      // #16: hero subtitle text uses intentionally muted brand color
      skipIssueIds: [16],
    },
    {
      label: "Web / Sign in modal — desktop",
      url: `${WEB_URL}/`,
      filePath: "apps/web/components/auth/SignInModal.tsx",
      viewport: { width: 1280, height: 800 },
      steps: [
        { action: "click", selector: "button:has-text('Sign in')" },
        { action: "wait", ms: 600 },
      ],
    },

    // Global search — seed/test handles are intentionally long; dropdown truncation is expected
    {
      label: "Web / Global search with query — desktop",
      url: `${WEB_URL}/`,
      filePath: "apps/web/components/search/GlobalSearch.tsx",
      viewport: { width: 1280, height: 800 },
      steps: [
        {
          action: "click",
          selector:
            "button[aria-label*='Search'], button:has-text('Search'), [placeholder*='Search']",
        },
        {
          action: "fill",
          selector:
            "input[type='search'], input[placeholder*='Search'], input[name='query']",
          value: "art",
        },
        { action: "wait", ms: 800 },
      ],
    },

    // Collections filter — cards at viewport bottom are partially in-view due to scroll; not overflow
    {
      label: "Web / Collections search filter — mobile",
      url: `${WEB_URL}/collections`,
      filePath: "apps/web/components/collections/CollectionFilters.tsx",
      viewport: { width: 375, height: 812 },
      steps: [
        {
          action: "click",
          selector:
            "button:has-text('All mediums'), select[name='medium'], [aria-label*='mediums']",
        },
        { action: "wait", ms: 500 },
      ],
    },

    {
      label: "Web / PlaceOfferModal — mobile",
      url: `${WEB_URL}/marketplace`,
      filePath: "apps/web/components/marketplace/PlaceOfferModal.tsx",
      viewport: { width: 375, height: 812 },
      steps: [
        { action: "click", selector: "button:has-text('Place offer')" },
        { action: "wait", ms: 600 },
      ],
      // #16: marketplace description text uses intentionally muted brand color
      skipIssueIds: [8, 16, 49],
    },
    {
      label: "Web / PlaceOfferModal — desktop",
      url: `${WEB_URL}/marketplace`,
      filePath: "apps/web/components/marketplace/PlaceOfferModal.tsx",
      viewport: { width: 1280, height: 800 },
      steps: [
        { action: "click", selector: "button:has-text('Place offer')" },
        { action: "wait", ms: 600 },
      ],
      // #23: CDN images loading in background marketplace grid
      skipIssueIds: [8, 16, 23, 49],
    },

    // ── ARTIST APP ───────────────────────────────────────────────────────────

    {
      label: "Artist / Home — mobile",
      url: `${ARTIST_URL}/`,
      filePath: "apps/artist/app/page.tsx",
      viewport: { width: 375, height: 812 },
      // #46: Home icon is filled/solid while others are outline — intentional active-state icon
      skipIssueIds: [46],
    },
    {
      label: "Artist / Home — desktop",
      url: `${ARTIST_URL}/`,
      filePath: "apps/artist/app/page.tsx",
      viewport: { width: 1280, height: 800 },
    },

    // Auth-required artist pages
    {
      label: "Artist / Dashboard — mobile (unauthed)",
      url: `${ARTIST_URL}/dashboard`,
      filePath: "apps/artist/app/dashboard/page.tsx",
      viewport: { width: 375, height: 812 },
      skipIssueIds: [8, 46, 49],
    },
    {
      label: "Artist / Dashboard — desktop (unauthed)",
      url: `${ARTIST_URL}/dashboard`,
      filePath: "apps/artist/app/dashboard/page.tsx",
      viewport: { width: 1280, height: 800 },
      skipIssueIds: [8, 49],
    },
    {
      label: "Artist / Earnings — mobile (unauthed)",
      url: `${ARTIST_URL}/earnings`,
      filePath: "apps/artist/app/earnings/page.tsx",
      viewport: { width: 375, height: 812 },
      // #23: avatar placeholder loading
      skipIssueIds: [8, 23, 46, 49],
    },
    {
      label: "Artist / Earnings — desktop (unauthed)",
      url: `${ARTIST_URL}/earnings`,
      filePath: "apps/artist/app/earnings/page.tsx",
      viewport: { width: 1280, height: 800 },
      skipIssueIds: [8, 49],
    },
    {
      label: "Artist / Claims — mobile (unauthed)",
      url: `${ARTIST_URL}/claims`,
      filePath: "apps/artist/app/claims/page.tsx",
      viewport: { width: 375, height: 812 },
      // #23: hero/banner area is a loading placeholder
      skipIssueIds: [8, 23, 46, 49],
    },
    {
      label: "Artist / Referrals — mobile (unauthed)",
      url: `${ARTIST_URL}/referrals`,
      filePath: "apps/artist/app/referrals/page.tsx",
      viewport: { width: 375, height: 812 },
      // #16: "Connect your studio wallet" placeholder is intentionally muted brand color
      skipIssueIds: [8, 16, 46, 49],
    },

    {
      label: "Artist / Privacy — mobile",
      url: `${ARTIST_URL}/privacy`,
      filePath: "apps/artist/app/privacy/page.tsx",
      viewport: { width: 375, height: 812 },
      skipIssueIds: [46],
    },
    {
      label: "Artist / Terms — mobile",
      url: `${ARTIST_URL}/terms`,
      filePath: "apps/artist/app/terms/page.tsx",
      viewport: { width: 375, height: 812 },
      skipIssueIds: [46],
    },

    // ── ARTIST APP — MODALS ──────────────────────────────────────────────────

    {
      label: "Artist / AddSocialsModal — mobile",
      url: `${ARTIST_URL}/dashboard`,
      filePath: "apps/artist/components/socials/AddSocialsModal.tsx",
      viewport: { width: 375, height: 812 },
      steps: [
        { action: "click", selector: "button:has-text('Add socials')" },
        { action: "wait", ms: 600 },
      ],
      skipIssueIds: [8, 46, 49],
    },
    {
      label: "Artist / WithdrawModal — mobile",
      url: `${ARTIST_URL}/earnings`,
      filePath: "apps/artist/components/earnings/WithdrawModal.tsx",
      viewport: { width: 375, height: 812 },
      steps: [
        { action: "click", selector: "button:has-text('Withdraw')" },
        { action: "wait", ms: 600 },
      ],
      skipIssueIds: [8, 49],
    },
    {
      label: "Artist / WithdrawModal — desktop",
      url: `${ARTIST_URL}/earnings`,
      filePath: "apps/artist/components/earnings/WithdrawModal.tsx",
      viewport: { width: 1280, height: 800 },
      steps: [
        { action: "click", selector: "button:has-text('Withdraw')" },
        { action: "wait", ms: 600 },
      ],
      skipIssueIds: [8, 16, 49],
    },
  ],

  // ── CHAOS ROUTES ─────────────────────────────────────────────────────────
  // Most interactive pages across all three apps.
  routes: [
    `${WEB_URL}/`,
    `${WEB_URL}/collections`,
    `${WEB_URL}/marketplace`,
    `${WEB_URL}/faq`,
    `${WEB_URL}/blog`,
    `${ARTIST_URL}/`,
    `${ARTIST_URL}/dashboard`,
  ],
};

export default config;
