/**
 * Fix Agent — Step 5 of the visual testing pipeline.
 *
 * Two modes:
 *
 *   'bugfix-branch' (default, nightly):
 *     All fixes committed to a single 'bugfix' branch. One PR opened (or
 *     updated) from bugfix → main. Branch is created from main if it doesn't
 *     exist yet.
 *
 *   'direct' (chaos / battle-hardening):
 *     Commits applied directly to the base branch. No PR, no review.
 *
 * Required env vars:
 *   DATABASE_URL          — Postgres connection string
 *   UI_FIX_GITHUB_TOKEN   — PAT with repo scope (Contents + Pull requests write)
 *   ANTHROPIC_API_KEY     — Anthropic API key (or set MOCK_LLM=true to skip)
 *
 * Optional:
 *   REPO_OWNER   — defaults to "NullStateLabs"
 *   REPO_NAME    — defaults to "artboxes"
 *   REPO_BRANCH  — defaults to "main"
 */

import { fileURLToPath } from "url";
import { Octokit } from "@octokit/rest";
import { getOpenTickets, resolveTicket, closePool, type BugTicket } from "../helpers/db-ticket.js";
import { generateCodeFix } from "../helpers/llm-vision.js";

const REPO_OWNER = process.env.REPO_OWNER ?? "NullStateLabs";
const REPO_NAME = process.env.REPO_NAME ?? "artboxes";
const BASE_BRANCH = process.env.REPO_BRANCH ?? "main";
const BUGFIX_BRANCH = "bugfix";

function getOctokit(): Octokit {
  const token = process.env.UI_FIX_GITHUB_TOKEN;
  if (!token) throw new Error("UI_FIX_GITHUB_TOKEN is not set");
  return new Octokit({ auth: token });
}

async function getFileContent(
  octokit: Octokit,
  filePath: string,
  ref: string = BASE_BRANCH
): Promise<{ content: string; sha: string }> {
  const { data } = await octokit.repos.getContent({
    owner: REPO_OWNER,
    repo: REPO_NAME,
    path: filePath,
    ref,
  });

  if (Array.isArray(data) || data.type !== "file") {
    throw new Error(`${filePath} is not a file`);
  }

  return {
    content: Buffer.from(data.content, "base64").toString("utf-8"),
    sha: data.sha,
  };
}

async function ensureBugfixBranch(octokit: Octokit): Promise<void> {
  try {
    await octokit.git.getRef({
      owner: REPO_OWNER,
      repo: REPO_NAME,
      ref: `heads/${BUGFIX_BRANCH}`,
    });
    console.log(`  Branch '${BUGFIX_BRANCH}' already exists`);
  } catch {
    const { data: mainRef } = await octokit.git.getRef({
      owner: REPO_OWNER,
      repo: REPO_NAME,
      ref: `heads/${BASE_BRANCH}`,
    });
    await octokit.git.createRef({
      owner: REPO_OWNER,
      repo: REPO_NAME,
      ref: `refs/heads/${BUGFIX_BRANCH}`,
      sha: mainRef.object.sha,
    });
    console.log(`  Created branch '${BUGFIX_BRANCH}' from ${BASE_BRANCH}`);
  }
}

async function commitFix(
  octokit: Octokit,
  opts: {
    branch: string;
    filePath: string;
    fixedContent: string;
    sha: string;
    ticketId: number;
    component: string;
  }
): Promise<void> {
  await octokit.repos.createOrUpdateFileContents({
    owner: REPO_OWNER,
    repo: REPO_NAME,
    path: opts.filePath,
    message: `fix(ui): ${opts.component} [ticket #${opts.ticketId}]`,
    content: Buffer.from(opts.fixedContent).toString("base64"),
    sha: opts.sha,
    branch: opts.branch,
  });
}

async function ensureBugfixPR(
  octokit: Octokit,
  fixed: Array<BugTicket & { id: number }>
): Promise<string> {
  const { data: existing } = await octokit.pulls.list({
    owner: REPO_OWNER,
    repo: REPO_NAME,
    head: `${REPO_OWNER}:${BUGFIX_BRANCH}`,
    base: BASE_BRANCH,
    state: "open",
  });

  const body = [
    `## UI Bug Fixes — auto-generated`,
    ``,
    ...fixed.map(
      (t) => `- **\`${t.component}\`** — ticket #${t.id}: ${t.reasoning}`
    ),
    ``,
    `> Fixes generated by the visual testing pipeline. Review before merging.`,
  ].join("\n");

  if (existing.length > 0) {
    await octokit.pulls.update({
      owner: REPO_OWNER,
      repo: REPO_NAME,
      pull_number: existing[0].number,
      body,
    });
    console.log(`  PR updated: ${existing[0].html_url}`);
    return existing[0].html_url;
  }

  const { data } = await octokit.pulls.create({
    owner: REPO_OWNER,
    repo: REPO_NAME,
    title: `fix(ui): visual regression fixes (${fixed.length} ticket${fixed.length !== 1 ? "s" : ""})`,
    body,
    head: BUGFIX_BRANCH,
    base: BASE_BRANCH,
  });

  console.log(`  PR opened: ${data.html_url}`);
  return data.html_url;
}

export interface FixAgentOpts {
  /**
   * 'bugfix-branch' (default): all fixes go to a single 'bugfix' branch, one PR opened.
   * 'direct': commits applied straight to the base branch. No PR.
   */
  mode?: "bugfix-branch" | "direct";
}

/**
 * Process all open bug tickets.
 * Does NOT close the Postgres pool — the caller is responsible for that.
 */
export async function runFixAgent(opts: FixAgentOpts = {}): Promise<void> {
  const mode = opts.mode ?? "bugfix-branch";

  console.log(`Fix Agent starting… (mode: ${mode})`);

  if (!process.env.UI_FIX_GITHUB_TOKEN) {
    console.warn("UI_FIX_GITHUB_TOKEN is not set — skipping auto-fix");
    return;
  }

  let octokit: Octokit;
  try {
    octokit = getOctokit();
  } catch (err) {
    console.warn(`Fix Agent: ${err} — skipping`);
    return;
  }

  const tickets = await getOpenTickets();
  console.log(`Found ${tickets.length} open ticket(s)`);

  if (tickets.length === 0) return;

  const targetBranch = mode === "direct" ? BASE_BRANCH : BUGFIX_BRANCH;

  console.log(`  Target: ${REPO_OWNER}/${REPO_NAME} @ ${targetBranch}`);

  if (mode === "bugfix-branch") {
    try {
      await ensureBugfixBranch(octokit);
    } catch (err) {
      console.error(
        `Fix Agent: cannot access ${REPO_OWNER}/${REPO_NAME} — check REPO_OWNER, REPO_NAME variables and UI_FIX_GITHUB_TOKEN permissions.\n  Error: ${err}`
      );
      return;
    }
  }

  const fixed: Array<BugTicket & { id: number }> = [];

  for (const ticket of tickets) {
    console.log(`\nProcessing ticket #${ticket.id}: ${ticket.component}`);

    try {
      // Always read from the target branch so sequential commits chain correctly
      const { content: fileContent, sha } = await getFileContent(
        octokit,
        ticket.file_path,
        targetBranch
      );

      const fixedContent = await generateCodeFix({
        filePath: ticket.file_path,
        fileContent,
        component: ticket.component,
        assertion: ticket.assertion,
        reasoning: ticket.reasoning,
      });

      if (fixedContent === fileContent) {
        console.log(`  No changes generated, skipping`);
        continue;
      }

      await commitFix(octokit, {
        branch: targetBranch,
        filePath: ticket.file_path,
        fixedContent,
        sha,
        ticketId: ticket.id,
        component: ticket.component,
      });

      await resolveTicket(ticket.id);
      fixed.push(ticket);

      console.log(`  Committed to '${targetBranch}' — ticket #${ticket.id} resolved`);
    } catch (err) {
      console.error(`  Failed to process ticket #${ticket.id}:`, err);
    }
  }

  if (mode === "bugfix-branch" && fixed.length > 0) {
    await ensureBugfixPR(octokit, fixed);
  }

  console.log(`\nFix Agent done. ${fixed.length}/${tickets.length} ticket(s) resolved.`);
}

// CLI entry point
if (fileURLToPath(import.meta.url) === process.argv[1]) {
  runFixAgent()
    .then(() => closePool())
    .catch((err) => {
      console.error(err);
      process.exit(1);
    });
}
