/**
 * Fix Agent — Step 5 of the visual testing pipeline.
 *
 * Reads open ui_bug_tickets from Postgres, uses Claude to generate a code fix,
 * then opens a GitHub PR with the corrected file.
 *
 * Required env vars:
 *   DATABASE_URL       — Postgres connection string
 *   GITHUB_TOKEN       — PAT with repo scope (Contents + Pull requests write)
 *   ANTHROPIC_API_KEY  — Anthropic API key (or set MOCK_LLM=true to skip)
 *
 * Optional:
 *   GITHUB_REPO_OWNER  — defaults to "NullStateLabs"
 *   GITHUB_REPO_NAME   — defaults to "artboxes"
 *   GITHUB_BASE_BRANCH — defaults to "main"
 */

import { Octokit } from "@octokit/rest";
import { getOpenTickets, resolveTicket, closePool } from "../helpers/db-ticket";
import { generateCodeFix } from "../helpers/llm-vision";

const REPO_OWNER = process.env.GITHUB_REPO_OWNER ?? "NullStateLabs";
const REPO_NAME = process.env.GITHUB_REPO_NAME ?? "artboxes";
const BASE_BRANCH = process.env.GITHUB_BASE_BRANCH ?? "main";

const octokit = new Octokit({ auth: process.env.GITHUB_TOKEN });

async function getFileContent(filePath: string): Promise<{ content: string; sha: string }> {
  const { data } = await octokit.repos.getContent({
    owner: REPO_OWNER,
    repo: REPO_NAME,
    path: filePath,
    ref: BASE_BRANCH,
  });

  if (Array.isArray(data) || data.type !== "file") {
    throw new Error(`${filePath} is not a file`);
  }

  return {
    content: Buffer.from(data.content, "base64").toString("utf-8"),
    sha: data.sha,
  };
}

async function createFixBranch(ticketId: number): Promise<string> {
  const { data: ref } = await octokit.git.getRef({
    owner: REPO_OWNER,
    repo: REPO_NAME,
    ref: `heads/${BASE_BRANCH}`,
  });

  const branchName = `fix/ui-bug-ticket-${ticketId}`;

  await octokit.git.createRef({
    owner: REPO_OWNER,
    repo: REPO_NAME,
    ref: `refs/heads/${branchName}`,
    sha: ref.object.sha,
  });

  return branchName;
}

async function commitFix(opts: {
  branch: string;
  filePath: string;
  fixedContent: string;
  sha: string;
  ticketId: number;
  component: string;
}): Promise<void> {
  await octokit.repos.createOrUpdateFileContents({
    owner: REPO_OWNER,
    repo: REPO_NAME,
    path: opts.filePath,
    message: `fix(ui): restore mobile stacking in ${opts.component} [ticket #${opts.ticketId}]`,
    content: Buffer.from(opts.fixedContent).toString("base64"),
    sha: opts.sha,
    branch: opts.branch,
  });
}

async function openPR(opts: {
  branch: string;
  ticketId: number;
  component: string;
  assertion: string;
  reasoning: string;
}): Promise<string> {
  const { data } = await octokit.pulls.create({
    owner: REPO_OWNER,
    repo: REPO_NAME,
    title: `fix(ui): ${opts.component} mobile layout regression [ticket #${opts.ticketId}]`,
    body: [
      `## UI Bug Fix — auto-generated`,
      ``,
      `**Component:** \`${opts.component}\``,
      `**Failed assertion:** ${opts.assertion}`,
      `**LLM reasoning:** ${opts.reasoning}`,
      ``,
      `> Auto-fix generated by the visual testing pipeline. Review before merging.`,
    ].join("\n"),
    head: opts.branch,
    base: BASE_BRANCH,
  });

  return data.html_url;
}

async function main() {
  console.log("Fix Agent starting…");

  if (!process.env.GITHUB_TOKEN) {
    console.error("GITHUB_TOKEN is not set — cannot open PRs");
    process.exit(1);
  }

  const tickets = await getOpenTickets();
  console.log(`Found ${tickets.length} open ticket(s)`);

  for (const ticket of tickets) {
    console.log(`\nProcessing ticket #${ticket.id}: ${ticket.component}`);

    try {
      const { content: fileContent, sha } = await getFileContent(ticket.file_path);

      const fixedContent = await generateCodeFix({
        filePath: ticket.file_path,
        fileContent,
        component: ticket.component,
        assertion: ticket.assertion,
        reasoning: ticket.reasoning,
      });

      if (fixedContent === fileContent) {
        console.log(`  No changes generated for ticket #${ticket.id}, skipping`);
        continue;
      }

      const branch = await createFixBranch(ticket.id);
      console.log(`  Created branch: ${branch}`);

      await commitFix({
        branch,
        filePath: ticket.file_path,
        fixedContent,
        sha,
        ticketId: ticket.id,
        component: ticket.component,
      });

      const prUrl = await openPR({
        branch,
        ticketId: ticket.id,
        component: ticket.component,
        assertion: ticket.assertion,
        reasoning: ticket.reasoning,
      });

      await resolveTicket(ticket.id);

      console.log(`  PR opened: ${prUrl}`);
      console.log(`  Ticket #${ticket.id} resolved`);
    } catch (err) {
      console.error(`  Failed to process ticket #${ticket.id}:`, err);
    }
  }

  await closePool();
  console.log("\nFix Agent done.");
}

main();
